name: PikpoMonorepo

packages:
  - apps/**
  - packages/**

scripts:
  app:
    run: |
      DEVICE=$(flutter devices | awk -F ' • ' '{print $1 " • " $2}' | fzf --prompt="Select a device: ") &&
      DEVICE_ID=$(echo $DEVICE | awk -F ' • ' '{print $2}') &&
      MODE=$(echo "debug\nrelease\nprofile" | fzf --prompt="Select a mode: ") &&
      melos exec --scope=pikpo_app -- flutter run --$MODE -d $DEVICE_ID
    description: Run the main entry-point for the `pikpo_app` app with selected device and mode.
  widgetbook:
    run: |
      DEVICE=$(flutter devices | awk -F ' • ' '{print $1 " • " $2}' | fzf --prompt="Select a device: ") &&
      DEVICE_ID=$(echo $DEVICE | awk -F ' • ' '{print $2}') &&
      MODE=$(echo "debug\nrelease\nprofile" | fzf --prompt="Select a mode: ") &&
      melos exec --scope=pikpo_widgetbook -- flutter run --$MODE -d $DEVICE_ID
    description: Run the main entry-point for the `pikpo_widgetbook` app with selected device and mode.
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  coverage:
    run: |
      melos exec -- very_good test --coverage --min-coverage 90 &&
      melos exec -- genhtml coverage/lcov.info -o coverage/html &&
      melos exec -- open coverage/html/index.html
    packageFilters:
      dirExists: test
    description: Run tests with coverage.
