name: PikpoMonorepo

packages:
  - apps/**
  - packages/**

scripts:
  dev_app:
    run: melos exec --scope=pikpo_app -- flutter run
    description: Run debug mode the main entry-point for the `pikpo_app` app.
  dev_widget:
    run: melos exec --scope=pikpo_widgetbook -- flutter run
    description: Run debug mode the main entry-point for the `pikpo_widgetbook` app.
  profile_app:
    run: melos exec --scope=pikpo_app -- flutter run --profile
    description: Run profile mode the main entry-point for the `pikpo_app` app.
  profile_widget:
    run: melos exec --scope=pikpo_widgetbook -- flutter run --profile
    description: Run profile mode the main entry-point for the `pikpo_widgetbook` app.
  release_app:
    run: melos exec --scope=pikpo_app -- flutter run --release
    description: Run release mode the main entry-point for the `pikpo_app` app.
  release_widget:
    run: melos exec --scope=pikpo_widgetbook -- flutter run --release
    description: Run release mode the main entry-point for the `pikpo_widgetbook` app.
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  coverage:
    run: |
      melos exec -- very_good test --coverage --min-coverage 90 &&
      melos exec -- genhtml coverage/lcov.info -o coverage/html &&
      melos exec -- open coverage/html/index.html
    packageFilters:
      dirExists: test
    description: Run tests with coverage.
